### ISSUE TITLE
[LinesCounter] Что же вы творите

### ISSUE THREAD

**Issue by pavel-b-novikov** [bobrovova/nsudotnet#1]
Вы зачем все сроки-то в файл читаете? Сколько памяти сжирает ваша программа?
Переделайте на нормальное, последовательное чтение файла по строкам.

**Comment by bobrovova** [comment]
Исправлено

https://github.com/bobrovova/nsudotnet/tree/master/Bobrov.Nsudotnet.LinesCounter

**Comment by pavel-b-novikov** [comment]
Едем дальше
```line.Substring (0, 2)```
Вы что, реально издеваетесь? Во-первых нахрена вы вносите модификации в считанную строку вообще? Эту задачу можно решить в принципе без модификации строк, но черт побери, использовать substring(0,2)... "а если у вас строка короче 2 символов" - это самое простое что приходит в голову, не говоря уже о быстродействии и памяти? В не на javascript-е пишете часом?

**Comment by bobrovova** [comment]
https://github.com/bobrovova/nsudotnet/tree/master/Bobrov.Nsudotnet.LinesCounter

Убрал substring. "это самое простое что приходит в голову, не говоря уже о быстродействии и памяти" - а что тяжелого в Length или я Вас не понял?
Нет, пишу на Ruby

**Comment by pavel-b-novikov** [comment]
Вот поэтому руби и отжирает столько памяти, что на нем пишут программисты с такой логикой. Вы своим .substring создаете каждый раз новую строку. Само собой, проверить её длину не составляет труда, конечно. А вот разметить под неё память, а потом убрать её - таки да, но вы этого почему-то не замечаете. На С, чтоли, попишите-вспомните malloc/free...

**Comment by bobrovova** [comment]
Согласен, с начала можно было лучше написать
