### ISSUE TITLE
[Calendar] Console.WriteLine ("ПН ВТ СР ЧТ ПТ СБ ВС");

### ISSUE THREAD

**Issue by pavel-b-novikov** [bobrovova/nsudotnet#2]
Так так так, а вот без хардкода имен дней недели как-то можно? Чтобы программа работала на компьютере с другой локалью?

**Comment by bobrovova** [comment]
Учтено

https://github.com/bobrovova/nsudotnet/tree/master/Bobrov.Nsudotnet.Calendar
