### ISSUE TITLE
[Enigma] Диспоз

### ISSUE THREAD

**Issue by pavel-b-novikov** [bobrovova/nsudotnet#4]
Где диспоз, где юзинги?

**Comment by bobrovova** [comment]
Добавил

https://github.com/bobrovova/nsudotnet/tree/master/Bobrov.Nsudotnet.Enigma

**Comment by pavel-b-novikov** [comment]
А .Close вы с какой целью регулярно вызываете? 
А MemoryStream вам зачем? Черт побери, если вы пишете на C# - пишите как на C#, а не как на java

**Comment by bobrovova** [comment]
MemoryStream: я правильно понял, на указателях переписать надо?

**Comment by pavel-b-novikov** [comment]
Чего? О_о Вы как-то сильно усложняете. MS там вообще не нужен от слова никак.

**Comment by bobrovova** [comment]
https://github.com/bobrovova/nsudotnet/tree/master/Bobrov.Nsudotnet.Enigma

1. Убрал
2. Из функции убрал, но в случае кодирования все равно нужен промежуточный массив, чтобы в base64 закодировать.

**Comment by pavel-b-novikov** [comment]
Да нет, я так погляжу, не убрали. Да и к тому же вы читаете все шифруемые данные в память. Зачем?

**Comment by bobrovova** [comment]
https://github.com/bobrovova/nsudotnet/tree/master/Bobrov.Nsudotnet.Enigma

Мне в кодировании без MemoryStream не обойтись, так как нужно еще закодировать данные перед выводом в файл. 
Сделал прямое копирование из потока в поток.

**Comment by pavel-b-novikov** [comment]
Пардон, а что вы кодируете перед выводом в файл?

**Comment by bobrovova** [comment]
Проблема в том, что когда я пишу напрямую байты в файл, то при декодировании вылазит ошибка  Bad PKCS7 Padding error: invalid... Единственное рабочее решение, которое помогло, было как раз кодировать в base64

**Comment by pavel-b-novikov** [comment]
Стоп, весь шифрованный файл в base64? O_o

**Comment by bobrovova** [comment]
Да

**Comment by pavel-b-novikov** [comment]
В base64 надо сохранять только ключи. Вы представляете какой размер будет у шифрованного файла? Никакой ошибки с PKCS возникать не должно - скорее всего вы что-то делаете не так. 
В любом случае, за конвертирование всего файла в base64 вам оторвут руки на первом же рабочем месте.

**Comment by bobrovova** [comment]
Это была вынужденная мера только в рамках учебной задачи. В реальном проекте понятно, что я бы так не сделал. 
Но на сайте xamarin'a официальный разработчик дал именно такой совет - использовать base64

**Comment by pavel-b-novikov** [comment]
Ссылку в студию, пожалуйста

**Comment by bobrovova** [comment]
https://forums.xamarin.com/discussion/16071/encryption-decryption-in-xamarin

**Comment by pavel-b-novikov** [comment]
Окей, наступать на баги mono тоже полезно. Пусть будет так, но в дальнейшем избегайте Рендала, особенно в мобильных приложениях.

**Comment by bobrovova** [comment]
Спасибо за совет и проверку
